### PR TITLE
Set up website for club

### LINKED ISSUE #1: Website for club
Inspiration / idea for layout: https://www.sfbitcoindevs.org/
Code repository: https://github.com/leishman/sf-bitcoin-devs

### PR DESCRIPTION
**Pull request by wbnns**
Resolves #1.

### CODE REVIEW

**Comment by nopara73** [comment]
Thank you very much!

- Would you mind making a PR on CoinShuffle++, which will be the next one, so I can see how to proceed forward. https://www.ndss-symposium.org/wp-content/uploads/2017/09/ndss201701-4RuffingPaper.pdf
- Would some magic CI in some other GitHub repo magically deploys the website or how's that happening?

@AvivMilner would you like to take over the maintenership of this repository as I barely found time to keep up with the preparation, recording and uploading the videos and maintaining this simple .md based repo in the first place.

**Comment by AvivMilner** [comment]
Yes @nopara73, I can manage this repo.

**Comment by wbnns** [comment]
@nopara73 

[Here's a link to a commit](https://github.com/wbnns/WasabiResearchClub/commit/436f2d46d16efd1fb2a01b290c1007fd5d47512f) that shows how to add a new meeting.  I have already set up CI on my fork, so that the website automatically updates every time `master` is updated.

Please don't hesitate to ask if you have any questions or if I can clarify the process further.

**Comment by nopara73** [comment]
Thank you! I added you as an maintainer. Would you mind setting up CI? If that's done IMO we're all ready to go using the website. Also can you email the cost of of the domain and a BTC address to @bharmat (balint.harmat@zksnacks.com) ? I think we're fine with you controlling it.

**Comment by wbnns** [comment]
@nopara73 

> Thank you! I added you as an maintainer. Would you mind setting up CI? If that's done IMO we're all ready to go using the website. 

Ok, great, thank you - done.

> Also can you email the cost of of the domain and a BTC address to @bharmat ([balint.harmat@zksnacks.com](mailto:balint.harmat@zksnacks.com)) ? I think we're fine with you controlling it.

No worries, if you all want it in the future I'll just transfer it over, then. No need to reimburse but appreciate the offer. Cheers.

Cc: @bharmat

**Pull request merged**
